### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by yuichiok** [QQbarAnalysis/QQbarAnalysis#20]
Hi @airqui ,

I pulled recent changes in this QQbarAnalysis 2021 branch but I am getting segmentation fault.
After some digging I found out that the problem happens when it tries to access jet thrust information.
In particular, between l.619-620 in QQbarAnalysis.cc
I can still get "d23" value so the collection and the object are there.

Were there any major update regarding this?

Best,
Yuichi

**Comment by airqui** [comment]
it works for me... I am guessing that the issue is in the steering file, please check the Thrust processor.
I have modified it to calculate the thrust of the jets, and not the thrust of the PFOs. The reason is that some PFOs are not part of the jets (i.e. classified as beam jets).

  <processor name="MySphere" type="Sphere">
    <parameter name="CollectionName" type="string"> RefinedJets </parameter>
    <parameter name="r_value" type="float"> 2.0 </parameter>
  </processor>

  <processor name="MySelectReconstructedParticle" type="SelectReconstructedParticle"> 
    <parameter name="inputCollectionName" type="string"> RefinedJets </parameter>
  </processor>
  <processor name="MyThrustReconstruction" type="ThrustReconstruction">  
    <parameter name="inputCollectionName" type="string"> RefinedJets </parameter> 
  </processor>

**Comment by airqui** [comment]
@yuichiok if this is not the problem.. I will investigate it when I come back from holidays (the 24th)

**Comment by yuichiok** [comment]
I see, that could be worth checking.
Sorry for interrupting your holiday!

**Comment by yuichiok** [comment]
Problem solved.
Thanks for the advice.
